### PR TITLE
fix: Added prefix to all css-classes

### LINKED ISSUE #31: Add prefix to CSS classes
Add a prefix to the CSS classes so they don't collide with user defined CSS classes.
Has to be a unique prefix like `og-`.

### PR DESCRIPTION
**Pull request by jensmo98**
Resolves #31

### CODE REVIEW

File: packages/org-chart/src/orgChart.ts [hunk 1]
```diff
@@ -1544,52 +1551,52 @@ function createNodeLineClass(
   } else {
     if (isTablet) {
       if (isLastRow && indexInRow === siblingsAmount - 1 && isOdd(indexInRow)) {
-        className = ' node-line-up-long';
+        className = ` ${lineUp}-long`;
       } else {
-        className = ` node-line-up-${isOdd(indexInRow) ? 'right-half' : 'left-half'} node-line-up`;
+        className = ` ${prefix}-node-line-up-${isOdd(indexInRow) ? 'right-half' : 'left-half'} ${lineUp}`;
```
Comment (Barsnes) [inline packages/org-chart/src/orgChart.ts:1556]: Should line 1556 use the `lineUp` var as well?

File: packages/org-chart/src/index.css [hunk 2]
```diff
@@ -78,12 +78,12 @@
   left: calc(50% - 1px);
 }
 
-.row-last-3-tablet::before {
-  height: calc(50% + 22px + calc(47.45px * var(--diff)));
+.och-row-last-3-tablet::before {
+  height: calc(50% + 22px + calc(47och-45px * var(--diff)));
```
Comment (Barsnes) [inline packages/org-chart/src/index.css:82]: Seems to be an issue here

**Review by Barsnes — CHANGES_REQUESTED** [review]
Found a bug, otherwise everything seems good!

**Review by Barsnes — APPROVED** [review]
🚀
